include:
  - template: Auto-DevOps.gitlab-ci.yml
  - local: '.build/conf/**/*.gitlab-ci.yml'

test:
  image: python:3.8-buster
  before_script:
    - pip install -r requirements.docs.txt
  stage: test
  script:
    - mkdocs build --strict --verbose --site-dir test
  artifacts:
    paths:
      - test

pages:
  image: python:3.8-buster
  before_script:
    - pip install -r requirements.docs.txt

  stage: deploy
  script:
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public
  only:
    - master
    - develop


#image: docker
#services:
#  - name: docker:dind
#    command: [ "--experimental" ]
#variables:
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_DRIVER: overlay2
#  DOCKER_BUILDKIT: 1
#  IMG_TAG: compile
#before_script:
#  - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
#
#depends:
#  stage: build
#  parallel:
#    matrix:
#      - BUILD: x86_64-unknown-linux-gnu
#      - BUILD: x86_64-pc-linux-gnu
#      - BUILD: x86_64-w64-mingw32
#      - BUILD: x86_64-unknown-freebsd
#      - BUILD: x86_64-apple-darwin
#  script:
#    - docker build --build-arg BUILD=$BUILD --target=$BUILD -t $DOCKER_REGISTRY/lthn/build:$BUILD .
#    - docker push $DOCKER_REGISTRY/lthn/build:$BUILD
