tool-gcc:build:
  stage: build
  image: docker
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  allow_failure: true
  variables:
    DOCKER_HOST: tcp://docker:2375
    IMAGE_TAG: "$CI_REGISTRY_IMAGE:tool-gcc"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --cache-from $IMAGE_TAG -t $IMAGE_TAG -f build-conf/tool/gcc/build.Dockerfile build-src
    - docker push "$IMAGE_TAG"
  rules:
    - changes:
        - build-conf/tool/gcc/build.Dockerfile
        - build-conf/tool/gcc/.gitlab-ci.yml

tool-gcc:deploy:
  stage: deploy
  needs: ["tool-gcc:build"]
  image: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    IMAGE_TAG: $CI_REGISTRY_IMAGE:tool-gcc
    DOCKER_TAG: $DOCKER_REGISTRY_IMAGE:tool-gcc
  services:
    - name: docker:dind
      command: [ "--experimental" ]
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker login -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD" $DOCKER_REGISTRY
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $DOCKER_TAG
    - docker push $DOCKER_REGISTRY/$DOCKER_TAG
  environment:
    name: tool-gcc
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      changes:
        - build-conf/tool/gcc/build.Dockerfile
        - build-conf/tool/gcc/.gitlab-ci.yml

