name: Server Compiler

on:
  push:
    paths:
      - images/compile.Dockerfile
      - .github/workflows/compile.yml
  pull_request:
    paths:
      - images/compile.Dockerfile
      - .github/workflows/compile.yml

jobs:
  base:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          target: build-base
          cache-to: ghcr.io/letheanvpn/build:base
          cache-from: ghcr.io/letheanvpn/build:base
          tags: lthn/build:base,ghcr.io/letheanvpn/build:base
          file: images/compile.Dockerfile
  compile:
    runs-on: ubuntu-latest
    needs: base
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          target: build-prep
          cache-to: ghcr.io/letheanvpn/build:server
          cache-from: ghcr.io/letheanvpn/build:server
          tags: lthn/build:server,lthn/build:latest,ghcr.io/letheanvpn/build:server,ghcr.io/letheanvpn/build:latest
          file: images/compile.Dockerfile

