name: lthn/build

on:
  push:
    paths:
      - compiler/images/*.Dockerfile
      - .github/workflows/compiler.yml
  pull_request:
    paths:
      - compiler/images/*.Dockerfile
      - .github/workflows/compiler.yml

env:
  CI_REGISTRY_IMAGE: ghcr.io/letheanvpn/build

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          context: compiler/src
          cache-to: $CI_REGISTRY_IMAGE:compile
          cache-from: $CI_REGISTRY_IMAGE:compile
          tags: lthn/build:compile,$CI_REGISTRY_IMAGE:compile
          file: compiler/images/compile.Dockerfile
  sources:
    runs-on: ubuntu-latest
    needs: compile

    strategy:
      matrix:
        os: [osx, linux, win]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          context: compiler/src
          build-args:
            BUILD:${{ matrix.os }}
          cache-to: $CI_REGISTRY_IMAGE:sources-${{ matrix.os }}
          cache-from: $CI_REGISTRY_IMAGE:sources-${{ matrix.os }}
          tags: lthn/build:sources-${{ matrix.os }},$CI_REGISTRY_IMAGE:sources-${{ matrix.os }}
          file: compiler/images/sources.Dockerfile

  depends:
    runs-on: ubuntu-latest
    needs: sources
    strategy:
      matrix:
        arch: [
          x86_64-unknown-linux-gnu, i686-pc-linux-gnu, arm-linux-gnueabihf,
          aarch64-linux-gnu, x86_64-w64-mingw32, i686-w64-mingw32,
          riscv64-linux-gnu, x86_64-unknown-freebsd
        ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          context: compiler/src
          build-args:
            BUILD:${{ matrix.os }}
          cache-to: $CI_REGISTRY_IMAGE:depends-${{ matrix.os }}
          cache-from: $CI_REGISTRY_IMAGE:depends-${{ matrix.os }}
          tags: lthn/build:depends-${{ matrix.os }},$CI_REGISTRY_IMAGE:depends-${{ matrix.os }}
          file: compiler/images/depends.Dockerfile