name: lthn/build

on:
  push:
    paths:
      - compiler/images/*.Dockerfile
      - .github/workflows/compiler.yml
  pull_request:
    paths:
      - compiler/images/*.Dockerfile
      - .github/workflows/compiler.yml

env:
  CI_REGISTRY_IMAGE: ghcr.io/letheanvpn/devops/build

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: |
          docker pull "$CI_REGISTRY_IMAGE:compile" || true
          docker build --squash --cache-from $CI_REGISTRY_IMAGE:compile -t $CI_REGISTRY_IMAGE:compile -f compiler/images/compile.Dockerfile compiler/src
          docker push "$CI_REGISTRY_IMAGE:compile"
  sources:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      matrix:
        os: [osx, linux, win]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: | 
          docker pull "$CI_REGISTRY_IMAGE:sources-${{ matrix.os }}" || true
          docker build --squash --build-arg BUILD=${{ matrix.os }} -t $CI_REGISTRY_IMAGE:sources-${{ matrix.os }} -f compiler/images/sources.Dockerfile compiler/src
          docker push "$CI_REGISTRY_IMAGE:sources-${{ matrix.os }}"
  depends:
    runs-on: ubuntu-latest
    needs: sources
    strategy:
      matrix:
        arch: [
          x86_64-unknown-linux-gnu, i686-pc-linux-gnu, arm-linux-gnueabihf,
          aarch64-linux-gnu, x86_64-w64-mingw32, i686-w64-mingw32,
          riscv64-linux-gnu, x86_64-unknown-freebsd
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          install: true
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          docker pull "$CI_REGISTRY_IMAGE:depends-${{ matrix.os }}" || true
          docker build --squash --build-arg BUILD=${{ matrix.os }} --cache-from $CI_REGISTRY_IMAGE:depends-${{ matrix.os }} -t $CI_REGISTRY_IMAGE:depends-${{ matrix.os }} -f compiler/images/depends.Dockerfile compiler/src
          docker push "$CI_REGISTRY_IMAGE:depends-${{ matrix.os }}"
