name: Server Compiler

on:
  push:
    paths:
      - images/compile.Dockerfile
      - .github/workflows/compile.yml
  pull_request:
    paths:
      - images/compile.Dockerfile
      - .github/workflows/compile.yml

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          target: build-base
          cache-to: ghcr.io/${OWNER_LC}/build:base
          cache-from: ghcr.io/${OWNER_LC}/build:base
          tags: lthn/build:base,ghcr.io/${OWNER_LC}/build:base
          file: images/compile.Dockerfile

