name: Docker CC

on:
  push:
    paths:
      - compiler/images/*.Dockerfile
      - .github/workflows/compiler.yml
  pull_request:
    paths:
      - compiler/images/*.Dockerfile
      - .github/workflows/compiler.yml

env:
  CI_REGISTRY_IMAGE: ghcr.io/dappserver/compiler

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          context: compiler/src
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: lthn/build:compile,${{ env.CI_REGISTRY_IMAGE }}:compile
          file: compiler/images/compile.Dockerfile
  sources:
    runs-on: ubuntu-latest
    needs: compile

    strategy:
      max-parallel: 1
      matrix:
        os: [osx, linux, win]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          context: compiler/src
          build-args:
            BUILD:${{ matrix.os }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: lthn/build:sources-${{ matrix.os }},${{ env.CI_REGISTRY_IMAGE}}:sources-${{ matrix.os }}
          file: compiler/images/sources.Dockerfile

  depends:
    runs-on: ubuntu-latest
    needs: sources
    strategy:
      fail-fast: false
      matrix:
        arch: [
          x86_64-apple-darwin11, x86_64-w64-mingw32, x86_64-unknown-linux-gnu,  x86_64-unknown-freebsd,
          arm-linux-gnueabihf, aarch64-linux-gnu, riscv64-linux-gnu, arm-linux-android, aarch64-linux-android
        ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          context: compiler/src
          build-args:
            BUILD:{{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: lthn/build:depends-${{ matrix.arch }},${{ env.CI_REGISTRY_IMAGE }}:depends-${{ matrix.arch }}
          file: compiler/images/depends.Dockerfile
