name: Docker CC

on:
  push:
    paths:
      - compiler/images/container.Dockerfile
      - .github/workflows/container.yml
  pull_request:
    paths:
      - compiler/images/container.Dockerfile
      - .github/workflows/container.yml

env:
  CI_REGISTRY_IMAGE: ghcr.io/dappserver/compiler

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-apple-darwin11, x86_64-apple-darwin,
          x86_64-pc-linux-gnu, i686-pc-linux-gnu, x86_64-unknown-freebsd, x86_64-w64-mingw32,
          x86_64-apple-darwin, aarch64-linux-gnu, arm-linux-gnueabihf, powerpc64-linux-gnu,
          powerpc64le-linux-gnu, riscv32-linux-gnu, riscv64-linux-gnu, s390x-linux-gnu,
          aarch64-linux-android, i686-linux-android, armv7a-linux-android
        ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          context: compiler/src
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ matrix.target }}
          tags: lthn/build:${{ matrix.target }}
          file: compiler/images/container.Dockerfile

