name: Builder Image

on:
  push:
    paths:
      - compiler/images/container.Dockerfile
      - .github/workflows/container.yml
  pull_request:
    paths:
      - compiler/images/container.Dockerfile
      - .github/workflows/container.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [
          i686-pc-linux-gnu, i686-linux-gnu, i686-w64-mingw32,
          x86_64-apple-darwin11, x86_64-w64-mingw32, x86_64-linux-gnu,  x86_64-unknown-freebsd,
          arm-linux-gnueabihf, aarch64-linux-gnu, riscv64-linux-gnu, arm-linux-android, aarch64-linux-android
        ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
        with:
          install: true
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          context: compiler/src
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ${{ matrix.target }}
          tags: lthn/build:libs-${{ matrix.target }}
          file: compiler/images/container.Dockerfile

