name: build:libs

on:
  push:
    branches: [ main ]
    paths:
      - .build/conf/libs/linux/base.Dockerfile
      - .github/workflows/libs.yml
  pull_request:
    paths:
      - .build/conf/libs/linux/base.Dockerfile
      - .github/workflows/libs.yml
    branches: [ main ]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: ghcr.io/letheanVPN/build:libs-linux-base
          tags: lthn/build:libs-linux-base
          file: .build/conf/libs/linux/base.Dockerfile
  libs:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        build: [
            libx, utils, cmake, boost, fontconfig
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: ghcr.io/letheanVPN/build:lib-linux-${{ matrix.build }}
          tags: lthn/build:lib-linux-${{ matrix.build }}
          file: .build/conf/libs/linux/${{ matrix.build }}.Dockerfile

  builder:
    runs-on: ubuntu-latest
    needs: libs
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        build: [
            linux, windows, android
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .build/src
          build-args: BUILD=${{ matrix.build }}
          tags: ghcr.io/letheanVPN/build:${{ matrix.build }}
          file: .build/conf/libs/${{ matrix.build }}.Dockerfile
