name: build:wallet

on:
  push:
    branches: [ main ]
    paths:
      - build-conf/wallet/linux/base.Dockerfile
      - .github/workflows/wallet.yml
  pull_request:
    paths:
      - build-conf/wallet/linux/base.Dockerfile
      - .github/workflows/wallet.yml
    branches: [ main ]

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: lthn/build:wallet-linux-base
          tags: lthn/build:wallet-linux-base
          file: build-conf/wallet/linux/base.Dockerfile
  libs:
    runs-on: ubuntu-latest
    needs: base
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        build: [
            libx, utils, cmake, boost, fontconfig
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: lthn/build:wallet-lib-linux-${{ matrix.build }}
          tags: lthn/build:wallet-lib-linux-${{ matrix.build }}
          file: build-conf/wallet/linux/${{ matrix.build }}.Dockerfile

  wallet:
    runs-on: ubuntu-latest
    needs: libs
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        build: [
            linux, windows, android
        ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: BUILD=${{ matrix.build }}
          tags: lthn/build:wallet-${{ matrix.build }}
          file: build-conf/wallet/${{ matrix.build }}.Dockerfile
